#!/usr/bin/env bash
# Display Holberton School 10 times, with Hi on the ninth
COUNTER=0
while [ $COUNTER -lt 10 ];do
	echo "Holberton School"
	if [ $COUNTER -eq 8 ]
	then
		echo "Hi"
	fi
	let COUNTER=COUNTER+1
done
