#!/usr/bin/env bash
# checks if file exits and print whether it does or not
# also checks if the files is empty and prints whether it is or not
if [ -e "./holbertonschool" ]
then
	echo "holbertonschool file exists"
	if [ -s "./holbertonschool" ]
	then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi
	if [ -f "./holbertonschool" ]
	then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
